apiVersion: v2
name: chutes-miner
description: Helm chart for chutes.ai miner
version: 0.1.5-rc0
appVersion: "0.0.1"
type: application
maintainers:
  - name: Jon Durbin
    email: jon@chutes.ai
  - name: namoray
    email: namoray@rayonlabs.ai
  - name: Kyle Widmann
    email: kyle@chutes.ai
kubeVersion: ">=1.19.0-0"
