---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chutes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chutes
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chutes
subjects:
- kind: ServiceAccount
  name: chutes
  namespace: chutes
roleRef:
  kind: ClusterRole
  name: chutes
  apiGroup: rbac.authorization.k8s.io
