apiVersion: v1
kind: Secret
metadata:
  name: chutes-sa-token
  namespace: chutes
  annotations:
    kubernetes.io/service-account.name: chutes
type: kubernetes.io/service-account-token
{{- $chutesToken := lookup "v1" "Secret" "chutes" "chutes-sa-token" }}
{{- if $chutesToken }}
data:
  {{- range $key, $value := $chutesToken.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}