- name: Restart Deployments
  ansible.builtin.command: >
    kubectl --kubeconfig {{ k3s_kubeconfig_path }} rollout restart deploy -n chutes
  register: restart_result
  changed_when: restart_result.rc == 0